### ISSUE TITLE
Port over all the SYE blogs since December 2016 into the new SYE site

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#111]
EiE have been writing blogs on the original SYE pombola site since our last port of blogs into the new site database in December 2016. It would be good if we could port all of these over into the blog on the new site so that the site looks complete and people have continuity when they're looking at the site.

The first blog we need to import is this one http://www.shineyoureye.org/blog/magus-non-confirmation-poli-tricks-nigerian-senate (if it's useful to have the page number it's at the top of page 3 : http://www.shineyoureye.org/blog/?page=3)

The last one we need to import is this one: http://www.shineyoureye.org/blog/sye-week-review-march-17-2017 (at the top of page http://www.shineyoureye.org/blog/?page=1)

The date range for the blogs is December 16 2016 to March 20 2017.

They should go into the http://sinatra.staging.shineyoureye.org/blog/ on the new site with the top three being shown under the news section on the home page.

**Comment by octopusinvitro** [comment]
Closing as this was achieved in https://github.com/theyworkforyou/shineyoureye-prose/pull/15
