### ISSUE TITLE
Design tweaks to homepage

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#112]
We now have feedback from SYE and they'd like a few design tweaks to the homepage. I *_think_* these are all design but they may not be :)

- [ ] Apply something to the pictures to make them less static. They have suggested a slider or carousel but I am sure that we could come up with something nicer!

![screen shot 2017-03-24 at 13 23 34](https://cloud.githubusercontent.com/assets/4170351/24296098/8ffebb5e-1095-11e7-930a-1564c494e6d8.png)

- [x] Reduce the size of the twitter  section to match the video section; this probably means showing only the most recent tweet if it contains a picture or article which 90% of their tweets do!

![screen shot 2017-03-24 at 13 29 26](https://cloud.githubusercontent.com/assets/4170351/24296199/03e3e6a2-1096-11e7-9424-c20038267764.png)

**Comment by octopusinvitro** [comment]
Second point addressed in #136

**Comment by JenMysoc** [comment]
The only further explanation from SYE was "The home page looks flat & static. As we change the officials, that'll add some variety but any other thing that can be added would be great, mindful of low bandwidth issues as well."

**Comment by zarino** [comment]
Closing in favour of the more specific #190.
