### ISSUE TITLE
Allow search to search for more than just PU number

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#113]
On the old site the search could search for a number of different things like area, people etc

![screen shot 2017-03-24 at 13 35 22](https://cloud.githubusercontent.com/assets/4170351/24297083/5a361522-1099-11e7-93c1-70d49ec0dd65.png)

But on the new sinatra site you can only seem to search for PU number:

![screen shot 2017-03-24 at 13 35 13](https://cloud.githubusercontent.com/assets/4170351/24297109/70b606d6-1099-11e7-8748-471ed11e726b.png)

Is it possible to make searching on the site a bit broader so that people can use that homepage search box to search the site for keywords (like people's names, area names, etc) and it bring up all results, as well as letting people search for the PU number.

**Comment by zarino** [comment]
Google Custom Search (the new name for Google Site Search) looks like a possibility here: https://developers.google.com/custom-search/

It seems to allow you to embed a `<gcse:searchresults-only>` custom HTML element into your page, and then pass in the search term via a URL query parameter, which the javascript pulls out and searches with: https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox

It’ll all depend on JavaScript support, though. And we’ll need to check whether it works ok in Opera Mini.
