### ISSUE TITLE
Person profile not appearing with the right name when trying to edit in prose

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#114]
Feedback from EiE: "I tried editing summary of some Representatives (Akintola Taiwo, Tony Nwulu and others), I clicked on ‘create it’ on prose .io but the profile did not appear with the right name."

**Comment by mhl** [comment]
I tried clicking "Edit summary" for Akintola Taiwo, clicked "Create It" and got to this page:

![example-new-post](https://cloud.githubusercontent.com/assets/7907/24353783/1a85e754-12e7-11e7-8eac-2619426c9160.png)

I assume what they mean is that the name of the file is `summaries/9b34c9ba-428f-4c08-9e05-716de04fcb06.md`. This is based on the internal ID of that representative, and shouldn't be changed. That ID associates the summary with the right person, so if they edit the body of the post (i.e. `## A New Post`), click the Save icon at the right and confirm the commit message, that will update the summary for Akintola Taiwo (after a few minutes' delay for the redeploy).

I'm going to close this unless there's more information about this.

(Note that it is possible we could get it to display the name of the person instead and hide the file name, but that would involve making changes to prose.io and getting them accepted by the maintainers of the project, so it'd be a big job.)
