### ISSUE TITLE
Display Senators and Representatives pages in a nicer way 

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#117]
Currently when you go to either http://sinatra.staging.shineyoureye.org/position/senator/ or http://sinatra.staging.shineyoureye.org/position/representative/ or http://sinatra.staging.shineyoureye.org/position/executive-governor/ you get a page that has large icons and info on the left but nothing on the right - there's only one profile per line. This means theres a) a lot of scrolling and b) the page can look somewhat empty

![screen shot 2017-03-24 at 15 06 59](https://cloud.githubusercontent.com/assets/4170351/24300210/9b79b962-10a3-11e7-96cc-34305ce97208.png)

It would be great if we could do something similar to what we've planned for the PA site's MP profiles page (eg showing the representatives scrolling horizontally or having more than one column with profile images in it - I leave that to design team magic!) and also have them arranged alphabetically by state.

**Comment by zarino** [comment]
This is currently blocked by https://github.com/theyworkforyou/shineyoureye-sinatra/issues/195

**Comment by chrismytton** [comment]
I've fixed #195 by adding a new `Mapit::Place#state` method in https://github.com/theyworkforyou/shineyoureye-sinatra/pull/210.

This allows you to do `person.area.state` to get to a person's state, regardless of what `person.area` is. So this ticket should now be unblocked.
