### ISSUE TITLE
Add a contact form to the about page

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#118]
I'm not sure if this is possible but EiE have requested there be a contact form on the SYE site on the about page. What do we need to know to make this happen?

**Comment by octopusinvitro** [comment]
I am using this for my personal site (also a static site) https://getsimpleform.com/

Googling shows up 
* Google forms https://support.google.com/docs/answer/87809?hl=en
* FormSpree https://formspree.io/
* A bunch of others in [this SO question](http://stackoverflow.com/questions/9533172/adding-contact-form-to-a-static-website)

I haven't used those though.
