### ISSUE TITLE
State government elections page still diverting to old site

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#121]
As in #116, the page at `/info/state-government-elections` is linking to member pages that point to the old SYE site.

At the moment we are still using the EP UUIDS as slugs for the member pages. However, we are planning to switch to using Pombola slugs for person pages (#43).

Since in this page they are using the Pombola slugs instead, I think it is better to wait until we finish #43 and then update the links here.

**Comment by mhl** [comment]
This is fixed now.
