### ISSUE TITLE
Move object construction to factories

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#123]
At the moment we have a coupling with the finder classes and the objects they create (for example, people classes are coupled to person classes because we have an explicit call to `.new` on those classes).

This finds us constantly changing these classes when the signature of the created classes changes (for example, having to pass an extra argument to the constructor of the people classes because the created class needs it). See for example commits 2272b581c7dfbc4387ff6e37ad14b12bc973eb36 and 4367744a2ec05c774a1da9043c90226669bdf6c0, there are a lot of files that change because we added a new argument to the constructor.

This is not a reason for this classes to change (and their tests, and the app.rb etc. etc.), so it may be better to create factories to be in charge of that and have the finder classes just ask the factory to create that object for them. This will also simplify the signature of the finder classes, from having a number of arguments needed for the creation of those objects to just passing one: the factory.

This would also end with the pain that is passing `baseurl` to everything.

**Comment by mhl** [comment]
Could you give one example of the signature of a factory method you'd like to introduce, and the change you'd make to use that?

**Comment by octopusinvitro** [comment]
At the moment we have:

```ruby
module MembershipCSV
  class People
    def initialize(csv_filename:, mapit:, baseurl:, identifier_scheme:)
      @csv_filename = csv_filename
      @mapit = mapit
      @baseurl = baseurl
      @identifier_scheme = identifier_scheme
    end

    private

    attr_reader :csv_filename, :mapit, :baseurl, :identifier_scheme

    def create_person(row)
      Person.new(
      person: row,
      mapit: mapit,
      baseurl: baseurl,
      identifier_scheme: identifier_scheme
      )
    end
  end
end
```

which produces :scream: like in commits 2272b58 and 4367744.

We could have a person factory like: 

```ruby
module MembershipCSV
  class PersonFactory
    def initialize(, mapit:, baseurl:, identifier_scheme:)
      @mapit = mapit
      @baseurl = baseurl
      @identifier_scheme = identifier_scheme
    end

    def self.build(person)
      Person.new(
        person: person,
        mapit: mapit,
        baseurl: baseurl,
        identifier_scheme: identifier_scheme
      )
    end

    attr_reader :mapit, :baseurl, :identifier_scheme
  end
end
```

and use it like:

```ruby
module MembershipCSV
  class People
    def initialize(csv_filename:, person_factory:)
      @csv_filename = csv_filename
      @person_factory = person_factory
    end

    private :csv_filename, :person_factory

    def create_person(row)
      person_factory.build(row)
    end
  end
end
```

and in tests we can have:

```ruby
    let(:people) do
      MembershipCSV::People.new(
        csv_filename: new_tempfile(contents),
        person_factory: FakeFactory.new(whatever_we_need)
      )
    end

    FakeFactory = Struct.new(:whatever_we_need) do
      def build(person)
        FakePerson.new(whatever_we_need_as_well)
      end
    end
```

This way we decouple the finder classes from the creation of other classes, so that they just find. At the moment they find AND create. So everytime the signature of the created classes changes, we have to change a lot of tests that have nothing to do with the created classes. That is a code smell, but it has been smelling since the introduction of the `baseurl` (which was my fault)! It just got worse :slightly_smiling_face: :hankey:

**Comment by mhl** [comment]
OK, this sounds fine to me. I'm wary of letting code become very factory heavy, but this seems like a good change.
