### ISSUE TITLE
Tables need design love 

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#130]
These tables can not be added classes. They are in the pages that the users will edit in plain markdown. So they need to be styled as simple `table`, `tr`, etc. elements.

They are enclosed in a `div` with `class="markdown infopages"`, though.

These are the pages with tables:

# Screenshots
http://localhost:9292/info/elections

![table](https://cloud.githubusercontent.com/assets/2157089/24460071/111e80ea-1495-11e7-89df-d5895edb44cc.png)

http://localhost:9292/info/2015-reruns

![reruns](https://cloud.githubusercontent.com/assets/2157089/24460530/78c558c6-1496-11e7-98fa-ba2a44952023.png)

http://localhost:9292/info/federal-ministries-and-nass-committees

![federal](https://cloud.githubusercontent.com/assets/2157089/24461064/f6d2ac5e-1497-11e7-84bf-121a748223ae.png)

see also:
* http://localhost:9292/info/state-government-elections
* http://localhost:9292/info/local-government-elections

**Comment by mhl** [comment]
@JenMysoc Could you add this to the design spreadsheet for estimation, possibly?

**Comment by zarino** [comment]
This will be super simple. Just a case of `@extend`-ing the Bootstrap table classes, or `@include`-ing the table mixins.

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye-sinatra/pull/154

![screen shot 2017-04-11 at 10 44 53](https://cloud.githubusercontent.com/assets/739624/24903053/23694c6c-1ea4-11e7-857e-b09d908d9f25.png)
