### ISSUE TITLE
Allow polls from polldaddy on SYE homepage

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#150]
On the old SYE homepage EiE have polls provided by PollDaddy

![screen shot 2017-04-07 at 15 03 48](https://cloud.githubusercontent.com/assets/4170351/24803527/7234c802-1ba3-11e7-8b3d-5fc000c19828.png)

They would like these on the new SYE homepage

**Comment by mhl** [comment]
We can just reuse the same poll widget from the old site - it could do with one of the designers looking at where to incorporate it onto the page, though, probably after consulting with EiE over how relatively important it is, to get the prominence right.
