### ISSUE TITLE
More interactive and appealing design for SYE homepage

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#176]
This is a bit of a placeholder as I have reminded EiE that they could get a designer to whip them up a bootstrap theme and submit it to us - as that was one of the reasons we made the site this way. However in the event that they don't find a designer they've asked if we can make the design of the homepage more interactive and appealing (they mentioned a carousel).

**Comment by GeorgieBurr** [comment]
The mock-up sent should be used as a guide as to what people are looking to see changed.

The homepage needs to:
- “It needs to immediately tell you what you’re trying to do.”
- Needs to show the 4 different types of role
- Search for Representative is a key function

Tickets created relating to the homepage re-design
 #180
#181 
#182
#183 
#184

**Comment by zarino** [comment]
Closing in favour of the more specific tickets #180 #181 #182 #183 #184 #191.

Feel free to open new tickets if you think something is missing!
