### ISSUE TITLE
Consolidate homepage styles with rest of the site

### ISSUE THREAD

**Issue by zarino** [theyworkforyou/shineyoureye-sinatra#18]
The homepage currently uses completely separate styles to the rest of the site. There’s a work-around in place to enable the main menu to be shared between the homepage and the rest of the site. But it’s a… weird situation, and contributes to the homepage having a completely different "feel" to the rest of the site.

The homepage should be just like all the other pages, and use the same styles.

This probably means integrating / re-creating the "new" homepage styles into the existing Pombola-derived styles. Or replacing both, at the same time, with something new.

**Comment by zarino** [comment]
Ok, I've looked at the new (homepage) styles we’re currently loading from the third-party site, and the old (ex-pombola) styles we’re compiling for the rest of the site. And I’ve had a chat with @mhl about where we see this product going. Here’s my thinking…

**I think we’re at a stage with this product that we *could* start over with the styling.** (Gasp!)

The "old" styles are hand-me-downs from Pombola, and aside from being sort of messily intertwined with Compass (#19), they’re much more complex than you’d expect for such a simple site: Partly because they’re a mixture of "core" (aka: mzalendo) styles plus nigerian overrides, but also because they create everything from scratch rather than building on an existing framework like Bootstrap or Foundation.

Meanwhile, the "new" styles are just a big blob of pre-compiled CSS, so whatever we do, we’re going to have to re-implement them somewhere in the main site’s Sass pipeline.

If we’re doing the work to fix these two things, there comes a point at which it's simpler to just start from a sturdy baseline (eg: bootstrap-sass) and then customise it to suit the product – eg: by "re-creating" the desired homepage layout, and making custom components for things like "lists of representatives" or whatever.

The advantage to using bootstrap-sass as a base (rather than the existing Pombola styles) is that new frontend developers coming to the site will be able to use a [whole bunch of pre-made components](http://getbootstrap.com/components), which will just work, rather than everything having to be styled from scratch. And for designers, the bootstrap-sass mixins and customisation options make it fairly easy to tweak and extend the theme without investing a massive amount of time.

**The steps for this would be:**

1. Remove everything in `sass/` and remove the custom `.css` links from the homepage template.
2. Get a Sass compilation pipeline running (@octopusinvitro is already onto this)
3. Get [bootstrap-sass](https://github.com/twbs/bootstrap-sass) into that pipeline, with `_variables.scss` etc files set up for people to customise the theme.
4. Customise the HTML templates (homepage, and inner pages) to use bootstrap components where possible, and write new HTML+CSS components for everything else.
5. End goal should be that the whole site is using bootstrap as a base, with a homepage design identical to the current one, but inner pages that match the "new" style.

Does this sound like a plan?

**Comment by octopusinvitro** [comment]
Yep, that sounds right :+1:
