### ISSUE TITLE
Better layout / styling for Twitter feed on homepage

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#180]
Feedback from Yemi was that the "ShineYourEye on Twitter" button looks a bit weird.

Also, the feed is taller than the video next to it (something that was supposedly fixed in #112 but appears not to have been) so that section of the homepage looks unbalanced.

<img width="1393" alt="screen shot 2018-10-03 at 10 22 39" src="https://user-images.githubusercontent.com/739624/46401939-4fed3400-c6f6-11e8-91fd-d4fc574821e6.png">

@zarino doesn’t think we should make the twitter widget any shorter – it’s already barely tall enough to display a single tweet. Perhaps instead we could add more above / below the video, so we balance it up that way?

**Comment by zarino** [comment]
Given #191 suggests removing the Quote between the "News" and social sections, we could try combining them into two columns of a single section. Like…

![screen shot 2018-10-04 at 16 30 22](https://user-images.githubusercontent.com/739624/46485032-d129f100-c7f2-11e8-8f5b-885950faecff.png)

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye-sinatra/pull/213
