### ISSUE TITLE
Homepage Redesign: Remove (?) duplicated Find your Representative search boxes

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#183]
Finding out who your representative is, is a key function of SyE.
The search box is duplicated in the top right corner of the homepage, consider removing.

**Comment by zarino** [comment]
* `.page--homepage .site-header { display: none; }`
* Replace "Find your Representative" button on homepage with a search box, using exactly the same markup and form action as the header search, so it sends people to either the PU lookup heroku app, or the google search results page, as expected.

**Comment by zarino** [comment]
Pull request here: https://github.com/theyworkforyou/shineyoureye-sinatra/pull/221

**Comment by zarino** [comment]
This has been deployed to the staging site: https://staging.shineyoureye.org/
