### ISSUE TITLE
Add "Search for your representative" box to every page?

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#185]
As finding out who are my representatives, is a key function of SyE, Yemi suggested we consider adding the Search box to every page.

**Comment by zarino** [comment]
Just to clarify – the PU (polling unit) search box is _already_ in the header of every page.

I think Yemi‘s comment was just that, once #113 is done, we should make sure the search box _continues_ to be on every page.

**Comment by zarino** [comment]
@GeorgieBurr make a note to check with Yemi, on our next catch-up call, as to whether she feels this ticket is closed, now that https://github.com/theyworkforyou/shineyoureye-sinatra/pull/215 lets you search for a representative by name from the search box at the top of any page on the site.

**Comment by GeorgieBurr** [comment]
@zarino @chrismytton  I just searched for the politician by name in the top right box and got the below message (see image)

Is the box searching for more than PU numbers? And if so, I expect the wording will need to be changed -  I can check with Yemi about this.

![screen shot 2018-10-30 at 10 54 02 2](https://user-images.githubusercontent.com/38856756/47713442-34604500-dc32-11e8-9b31-5747a81768a1.png)

**Comment by zarino** [comment]
@GeorgieBurr The clever searching feature is up on https://staging.shineyoureye.org, but not https://www.shineyoureye.org yet. You used the latter.

**Comment by GeorgieBurr** [comment]
Dur! Sorry! (Embarrassed face)

**Comment by zarino** [comment]
Also, I’m not sure Lai Mohammed is actually an elected representative in Nigeria? He doesn’t appear on shineyoureye.org at least, and [his Wikipedia page](https://en.wikipedia.org/wiki/Lai_Mohammed) only mentions that he’s a Minister, not a representative or a senator.

**Comment by zarino** [comment]
Closing as they seem happy with this.
