### ISSUE TITLE
Add a "contact" form to Politicians profile page?

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#187]
A simple version of FormSpree cannot be added to Politicians pages.  Chris to have a think about other options and the difficulty level and time required for other options.

**Comment by zarino** [comment]
The context here was that Yemi felt it was confusing to dump people into their native email client (which is what the existing `mailto:` links do). So she suggested handling the composing and sending of emails within SYE itself, rather than handing off to an external email application.

**Comment by chrismytton** [comment]
Pull request to change mailto: link to text here: https://github.com/theyworkforyou/shineyoureye-sinatra/pull/236
