### ISSUE TITLE
Remove Compass Sass dependency

### ISSUE THREAD

**Issue by zarino** [theyworkforyou/shineyoureye-sinatra#19]
Compass was a library that included a bunch of pre-made Sass mixins, but it’s [no longer being maintained](https://github.com/Compass/compass), and we don’t actually derive that much benefit from it in the [original Pombola sites](https://github.com/mysociety/pombola/).

When ShineYourEye was ported from Pombola to Jekyll, the styles weren't touched at all, meaning the Compass dependency was maintained.

Now we’re looking at consolidating the homepage styles into the main Sass pipeline (https://github.com/theyworkforyou/shineyoureye-sinatra/issues/18) maybe this is an opportunity to re-write the styles, to remove the Compass dependency?

**Comment by octopusinvitro** [comment]
I would say, go for it :+1: 
Let's see what @mhl thinks :slightly_smiling_face:

**Comment by mhl** [comment]
I'd be very happy to get rid of the compass dependency.

**Comment by zarino** [comment]
Compass was removed as part of e90c08736fa70794ee0c71898937d0ef9617bd43! 🚀
