### ISSUE TITLE
Randomly select people to show on the homepage

### ISSUE THREAD

**Issue by zarino** [theyworkforyou/shineyoureye-sinatra#190]
The EIE team would like the homepage to feature different people each time you visit.

<img width="1398" alt="screen shot 2018-10-03 at 10 14 53" src="https://user-images.githubusercontent.com/739624/46401548-37304e80-c6f5-11e8-9459-c999e5f7de78.png">

We could potentially do this entirely client-side (just embed a bunch of hidden people into the homepage, and reveal one at random on page load).

**Comment by zarino** [comment]
@chrismytton Does SYE currently have any concept of State Assembly members?

**Comment by chrismytton** [comment]
@zarino No, at the moment SYE only knows about Representatives, Senators and Governors.

**Comment by zarino** [comment]
Ok, so two issues here that hopefully @chrismytton can help solve:

1. The homepage currently gets its 3 people via `summaries_finder.find_featured` (see the `get '/' do` block in `app.rb`) – whereas I think we now want it to just select X number of random people from each of the 3 (well, 4) representative types, and pass them to the template. So we’ll need to swap that out, I think?
2. The mockup shows State Assembly members as a 4th representative type, but SYE currently has no concept of State Assembly members.

Once those are sorted, my plan would be:

1. When the homepage is rendered (remember, this will only happen "once" – when the scraper converts the site into static files, to be served at shineyoureye.org) the homepage template is given 10 random governors, 10 random senators, etc etc, and it prints them all out to the HTML, hiding all but the first one of each type.
2. Then, when a visitor loads the page, some JavaScript picks a random person from each group of 10 to show, and hides all the rest. Because we’re not loading anything by ajax, it should be dead fast.

10 is my guess at a number that stikes a good balance between not bloating the HTML payload too much, but still feeling _fairly_ random to a typical visitor. It could be that we can get away with a higher number, if the selection doesn’t feel random enough.

**Comment by chrismytton** [comment]
@zarino I've opened https://github.com/theyworkforyou/shineyoureye-sinatra/pull/238, which selects 10 random people of each type and passes the into the template, so I think that's ready for you to pickup now.
