### ISSUE TITLE
Need a way to tell which *State* a Federal Constituency / Senatorial District is in

### ISSUE THREAD

**Issue by zarino** [theyworkforyou/shineyoureye-sinatra#195]
#117 requires grouping people by "State".

SYE already has a concept of States (see http://www.shineyoureye.org/place/is/state/) but as you’ll see from http://www.shineyoureye.org/place/abia/ (where only one representative—the Governor—is listed as belonging to this State) it’s not clever enough to know which Senators and Representatives represent Senatorial Districts or Federal Constituencies _within_ that State.

SYE *does* seem know which State is the "parent" of a given Senatoral District or Federal Constituency (see http://www.shineyoureye.org/place/is/senatorial-district/). So the mapping must be in there somewhere.

Ideally, to do #117, I need a nice quick way of pulling out the state that a person is from, eg: `person.area.state` (which should work regardless of whether the `person.area` is a State, a Senatorial District, or a Federal Constituency).

**Comment by zarino** [comment]
Now I look at it, https://github.com/theyworkforyou/shineyoureye-sinatra/issues/177 is a bug report about this exact issue, and would be probably fixed by a mapping between parent and children areas.

**Comment by chrismytton** [comment]
Pull request to add a `Mapit::Place#state` method here: https://github.com/theyworkforyou/shineyoureye-sinatra/pull/210.

That change allows you to use `person.area.state` to get to an area's state, without worrying about whether `person.area` is a State, a Senatorial District, or a Federal Constituency.
