### ISSUE TITLE
Homepage redesign: Add contact address, email address and twitter handle to Homepage footer

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#223]
They want the email address (not a link to contact page) and twitter handle added to the footer.

**Comment by zarino** [comment]
@GeorgieBurr I don’t remember "contact address" being mentioned in the meeting, and it’s not in [the meeting notes](https://docs.google.com/document/d/1yfd-RO55CAl-wwtchJoP4J0c_StS9mNLfRMeUYH4guw/edit). It was just email address and twitter handle, I think.
