### ISSUE TITLE
Places/States: Replace "pin" thumbnails with images

### ISSUE THREAD

**Issue by GeorgieBurr** [theyworkforyou/shineyoureye-sinatra#226]
Replace ”pin” thumbnails on /place/is/state with custom images (EiE will send over these images)
@chrismytton  will need to estimate the time this job will take

**Comment by emilydrk** [comment]
Estimate: 1 day.

**Comment by GeorgieBurr** [comment]
Seun has sent the images over. We have suggested we can add the images this year.

EiE have requested that they would like to be able to change this data themselves, which begs the image will be stored etc. We can discuss this in the meeting about data, in relation to #174 
We have said this work will need to be estimated, and would then take place next year.

**Comment by zarino** [comment]
Pull request here https://github.com/theyworkforyou/shineyoureye-sinatra/pull/245 ready for @chrismytton to take a look at.
