### ISSUE TITLE
Skills description for developers needed to support ShineYourEye

### ISSUE THREAD

**Issue by emilydrk** [theyworkforyou/shineyoureye-sinatra#258]
Write a brief skills description for what EiE need to look for in local developers who might be able to support SYE now.

**Comment by chrismytton** [comment]
Brain dump of various things this project is using

- [Ruby](https://www.ruby-lang.org/en/) - The code in this repo is written in Ruby
- [Sinatra](http://sinatrarb.com/) - A lightweight Ruby web framework
- [GitHub](https://github.com) - Where the code for the project is hosted
- [GitHub Pages](https://pages.github.com/) - This is where https://www.shineyoureye.org/ is hosted
- [Travis CI](http://travis-ci.org/) - Runs the tests for shineyoureye-sinatra and builds the site when [shineyoureye-prose](https://github.com/theyworkforyou/shineyoureye-prose) is updated.
- [prose.io](http://prose.io/) - Content editor for static sites, this is what EiE use to edit blog posts and pages stored in the shineyoureye-prose repo
- [morph.io](https://morph.io/) - Hosts the scraper for the nigeria-state-governors data
- [nigeria.mapit.mysociety.org](http://nigeria.mapit.mysociety.org/) - Nigerian instance of mapit hosted by mySociety
- [EveryPolitician](http://everypolitician.org/) - We're pulling the NA and Senate data from here
- [Sass](https://sass-lang.com/) - Used in the stylesheets

**Comment by emilydrk** [comment]
@chrismytton I can take what you've written above and draft it into an email for Yemi now.

**Comment by chrismytton** [comment]
> @chrismytton I can take what you've written above and draft it into an email for Yemi now.

Ah that'd be great, thanks @emilydrk!

**Comment by chrismytton** [comment]
@emilydrk I think the headline should be "Web Developer with Ruby experience and familiarity with GitHub", those are the core skills needed to understand how the site works and how it's hosted.
