### ISSUE TITLE
Switch to using image_cache instead of politician-image-proxy

### ISSUE THREAD

**Issue by mhl** [theyworkforyou/shineyoureye-sinatra#33]
Apparently we shouldn't be using the cache of images from https://github.com/mysociety/politician-image-proxy - that has thumbnail images for every country, for the use of everypolitician.org. We need larger thumbnails and the original images for the site, and to do that we should run https://github.com/everypolitician/image_cache instead. It can store images in https://github.com/theyworkforyou/nigeria-images which @chrismytton created previously. He says that's "essentially just a slightly tidied up and country-specific version of https://github.com/mysociety/politician-image-proxy/blob/c4a728598ecbbdda1a17358335e27a70b8062d67/scraper.rb "

**Comment by octopusinvitro** [comment]
Fixed in https://github.com/theyworkforyou/shineyoureye-sinatra/pull/45
