### ISSUE TITLE
Implement pagination in list pages

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#47]
In pages that are a list of things, for example:

* Posts
* People
* Places

Implement pagination so that only a number of them are loaded, say 10 for example.

**Comment by mhl** [comment]
I don't necessarily agree about this - the pages load super fast and we lazy-load the images, so what's the benefit to the user in paginating the results?

**Comment by octopusinvitro** [comment]
Mmmm... scrolling, in particular in tiny screens like tablets or mobile, but more mobile. I think Nigerian users navigate the internet more through mobile than fancy desktop :phone: 

https://ondeviceresearch.com/blog/nigeria-leader-mobile-web-traffic

**Comment by mhl** [comment]
Yes, I know mobile use is high in Nigeria (we see a huge amount of Opera Mini use of ShineYourEye: https://github.com/mysociety/pombola/blob/master/docs/browser-share.md ) but is it necessarily the case that scrolling is hard on these devices? Even on very basic smartphones, scrolling is easier and more intuitive than on desktop and certainly easier than navigating pagination links, in my experience. @zarino / @wrightmartin - do you have a view on this?

**Comment by octopusinvitro** [comment]
I'm OK with leaving it out then :+1:
