### ISSUE TITLE
events aren't being listed at the moment

### ISSUE THREAD

**Issue by mhl** [theyworkforyou/shineyoureye-sinatra#48]
Presumably this is because none them have their event date set - we should go through and manually set the data on at least the most recent 5 events on prose.io for the purposes of demoing the site.

This refers to both the front page and the events page:

* http://sinatra.staging.shineyoureye.org/
* http://sinatra.staging.shineyoureye.org/info/events

**Comment by octopusinvitro** [comment]
Events are not shown because there are no events :laughing: 

--> https://github.com/theyworkforyou/shineyoureye-prose/tree/gh-pages/events

**Comment by mhl** [comment]
There is an event now :)

The strange thing going on with events is that the event list page at `/info/events` works on the Sinatra site, but it's missing after being scraped. I believe that what's happening is the following:

* `/info/events` (the event list page) is scraped first by wget, which creates an HTML file `info/events`
* Later the page `/info/events/fct-lga-polls-2016` is scraped, and `wget`, in its wisdom, replaces the `info/events` file with an `info/events` directory and puts a `fct-lga-polls-2016` HTML file in there.

So, the index page is saved and then deleted by `wget`. That's an issue I suggest we don't get into :)

However, this does expose another problem, and fixing that would also fix the 404: my intention was that the URL path for an individual event should look like `/events/fct-lga-polls-2016`, not `/info/events/fct-lga-polls-2016`. If we fix that then the problem with the event listing (pseudo-)info page being deleted goes away.
