### ISSUE TITLE
Add maps to place pages

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#53]
Currently, the place pages are showing a default image of a place:

![sinatra](https://cloud.githubusercontent.com/assets/2157089/23064944/d4aace60-f50a-11e6-88a6-d4133ad8f0c7.png)

Where that image is now, there should be a map with the demarcation of the region, as in the Pombola version of the site:

![pombola](https://cloud.githubusercontent.com/assets/2157089/23064941/d0b26a20-f50a-11e6-8f02-d8e882d6e9f7.png)

**Comment by zarino** [comment]
Ping me when you’ve added the map markup to the page – I’d be tempted to make the map bigger!

**Comment by GeorgieBurr** [comment]
The EiE team would like to use a map to represent places, as per the recommendations in their PDF. See:

<img width="1280" alt="screen shot 2018-11-07 at 12 06 37" src="https://user-images.githubusercontent.com/38856756/48130912-1a53e180-e286-11e8-9b6d-53f6329eaaab.png">

<img width="1280" alt="screen shot 2018-11-07 at 12 06 41" src="https://user-images.githubusercontent.com/38856756/48130966-453e3580-e286-11e8-8d63-37a483335ba4.png">
