### ISSUE TITLE
Make commits to prose trigger a deploy

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#62]
So that everytime a user enters new data in [the prose repository](https://github.com/theyworkforyou/shineyoureye-prose), for example, adding a new blog post, editing existing files, etc., a deploy is triggered automatically.

**Comment by JenMysoc** [comment]
Feedback from EiE suggests that they've tried adding or editing the Elections page, the blog posts and adding summaries to people on the people pages but currently these can't be seen on the site as the site hasn't deployed them

**Comment by octopusinvitro** [comment]
The description in [the last commit]( https://github.com/theyworkforyou/shineyoureye-static/commit/8f2af9a007e9fbdf181eea85a894ca026c8ec512) in the `shineyoureye-static` repo seems to be pointing to [the last commit](https://github.com/theyworkforyou/shineyoureye-prose/commits/gh-pages) of the `shineyoureye-prose` repo at the moment of writing this ([22ce735](https://github.com/theyworkforyou/shineyoureye-prose/commit/22ce7355571359217af80e499fd12bb8ba998e92)):

```
 Automated commit of generated static site data

The shineyoureye-sinatra version was: 22ce7355571359217af80e499fd12bb8ba998e92
The shineyoureye-prose version was: 47ea032f49df9e28e755068378b8f647d9062950
```

**Comment by octopusinvitro** [comment]
Closing for the reasons stated above after confirming with @mhl
