### ISSUE TITLE
Undo the harm done the shipping week

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#64]
The shipping week and particularly the shipping day we committed a lot of code of not the best quality. So remember to add tests where they are missing, tidy up the code where it is messy, refactor what needs to be refactored, etc. as soon as possible [so that we don't carry on this technical debt](https://infinum.co/the-capsized-eight/is-your-business-sinking-into-technical-debt) with us.

<blockquote class="twitter-tweet" data-lang="en-gb"><p lang="en" dir="ltr">&quot;What is technical debt?&quot; Technical debt is hard to explain, but a picture is worth a thousand words. <a href="https://twitter.com/hashtag/programming?src=hash">#programming</a> <a href="https://twitter.com/hashtag/softwaredevelopment?src=hash">#softwaredevelopment</a> <a href="https://t.co/AG2L3VDuKZ">pic.twitter.com/AG2L3VDuKZ</a></p>

![tetris](https://cloud.githubusercontent.com/assets/2157089/23105719/4ffdd41e-f6db-11e6-8836-2c55ed4d58a0.jpeg)

&mdash; Jedd Ahyoung (@Jedd_Ahyoung) <a href="https://twitter.com/Jedd_Ahyoung/status/826551935822077952">31 January 2017</a></blockquote>

## List of things to fix

* ~Since we are now exposing `person`, in the person page, methods like this should probably go:~
```ruby
def email
  person.email
end
```
* ~There are no tests for email in the person page or in the person integration tests (web tests)~
* ~There is no test for the edit link in summaries~
* Improve the code in the route of a search page
* ~In the mappings class, rename the `pombola_slugs_to_mapit_ids_ignore_last` to ignore type, so that the comment is not needed.~
* It feels like some of our `find_something` calls should be done inside the pages. :thinking: 
* `current_memberships` in the EP person class is not been used by anybody, so it should be private.
* remove all nokogiris that are not needed, for example those inside of describe blocks
* `must_equal(true)` use `assert` instead, maybe... we mix assertions and expectations a bit, we will have to decide maybe on one ¿?
* ~add a test for when a state does not exist~
* Move the alias method move to the top in the mapit-place class
* Extract pombola slug method in the wrapper
* page place --> temporal coupling in place.parent. I had to remember to add it to a test. Maybe change the relationship, instead of searching for the parent, search for the children. Or send the parent already in the hashed data to the place class? :thinking: also, two ways of providing a parent is confusing
* move all test doubles to test_doubles <-- :thinking: 
* `is_child_area?` is type checking, not convinced that it was a good idea to introduce that
* For consistency, maybe update the way we are reading the mapit json files. Tests are a controlled environment, we decide where to save files (`mapit_data_for_area_type` in test_helper)
* `is_in_mapit_area?` should be in the person
* memoize find methods in ep people
* Low priority: baseurl. Passing mapit to `PeopleByLegislature` because people need it is a similar problem. The latter could be solved if mapit ids are added to EP areas. I've been thinking about this and I think maybe having object factories could help extract this things out and manage them all in the factory that is in charge of creating them, that way we don't have to go all the way down the stack, just create the factories we need... still need to think about it deeper though.

**Comment by mhl** [comment]
We've dealt with a lot of these things now; some of the others aren't high priority to deal with, either, so I'm closing this and we can create individual tickets for any that are still worth looking at soon.
