### ISSUE TITLE
Change the ndash character in Pombola, for Senator DARIYE JOSHUA CHIBI

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#75]
Change the ndash character in Pombola, for politician with EP UUID `0de9e40b-52bc-459f-978b-2aea514eec79` (Senator DARIYE JOSHUA CHIBI), so that when we run the `bin/build_summaries.rb` script again we don't get a bad encoded character, as it happened in https://github.com/theyworkforyou/shineyoureye-prose/pull/5

It would also be a good idea to check if there are any other obviously problematic characters in the summaries.

**Comment by mhl** [comment]
I did this at the end of last week - you can see the en-dash here: http://www.shineyoureye.org/person/dariye-joshua-chibi/

**Comment by octopusinvitro** [comment]
Ah sorry! :sweat_smile:
