### ISSUE TITLE
make any wget errors (4xx and 5xx anyway) cause the deploy to fail

### ISSUE THREAD

**Issue by mhl** [theyworkforyou/shineyoureye-sinatra#95]
Once #93 is merged and the errors described in #94 have been
fixed, it would be a good idea to cause the deploy to fail if there
are any errors from wget. (We already have a `WGET_EXIT_CODE`
variable, so this should be easy to do.)

(Relatedly, we should check that we will get notifications if this
happens from a automated deploy running on Travis.)

**Comment by octopusinvitro** [comment]
#93 merged :+1:

**Comment by octopusinvitro** [comment]
#94 closed :+1:
